Bookstore/Models/BookViewModel.cs
using Microsoft.AspNetCore.Http;

namespace Bookstore.Models
{
    public class BookViewModel
    {
        public string Title { get; set; }
        public int? YearPublished { get; set; }
        public int? NumPages { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
        public IFormFile FrontPageFile { get; set; }
        public string DownloadURL { get; set; }
        public int AuthorId { get; set; }
    }
}

Bookstore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net;
using Bookstore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using static System.Net.WebRequestMethods;

namespace Bookstore.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookstoreContext _context;

        public BooksController(BookstoreContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index(string bookGenre, string searchString)
        {
            
            IQueryable<Book> books = _context.Book.Include(b => b.Author).Include(b => b.Genres).ThenInclude(bg => bg.Genre).Include(b => b.Reviews); 

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => b.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(bookGenre))
            {
                books = books.Where(b => b.Genres.Any(bg => bg.Genre.GenreName == bookGenre));
            }

            var genres = _context.Genre.OrderBy(g => g.GenreName).Select(g => g.GenreName).Distinct();

            
            var viewModel = new BookGenreViewModel
            {
                Books = await books.ToListAsync(),
                Genres = new SelectList(await genres.ToListAsync())
            };

            return View(viewModel);
            
        }
       
        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            var reviews = await _context.Review
                .Where(r => r.BookId == id)
                .Select(r => r.Comment) 
                .ToListAsync();

            ViewBag.Reviews = reviews;

            return View(book);
        }
        // GET: Books/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName");
            ViewBag.Genres = new SelectList(_context.Set<Genre>(), "Id", "GenreName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadURL,AuthorId")] Book book, IFormFile file1, IFormFile file2, List<int> selectedGenres)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null && file1.Length > 0 && file2 != null && file2.Length > 0)
                {
                    var fileName1 = Path.GetFileName(file1.FileName);
                    var filePath1 = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", fileName1);

                    var fileName2 = Path.GetFileName(file2.FileName);
                    var filePath2 = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", fileName2);

                    using (var stream = new FileStream(filePath1, FileMode.Create))
                    {
                        await file1.CopyToAsync(stream);
                    }

                    using (var stream = new FileStream(filePath2, FileMode.Create))
                    {
                        await file2.CopyToAsync(stream);
                    }

                    
                    book.FrontPage = "../UploadedFiles/" + fileName1;
                    book.DownloadURL= "../UploadedFiles/" + fileName2;
                }

                if (selectedGenres != null && selectedGenres.Count > 0)
                {
                    book.Genres = new List<BookGenre>();
                    foreach (var genreId in selectedGenres)
                    {
                        var genre = await _context.Genre.FirstOrDefaultAsync(g => g.Id == genreId);
                        if (genre != null)
                        {
                            book.Genres.Add(new BookGenre { Genre = genre });
                        }
                    }
                }
               
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FirstName", book.AuthorId);
            ViewBag.Genres = new SelectList(_context.Set<Genre>(), "Id", "GenreName");
            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            
            
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FirstName", book.AuthorId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadURL,AuthorId")] Book book, IFormFile file1, IFormFile file2)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (file1 != null && file1.Length > 0 && file2 != null && file2.Length > 0)
                {
                    var fileName1 = Path.GetFileName(file1.FileName);
                    var filePath1 = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", fileName1);

                    var fileName2 = Path.GetFileName(file2.FileName);
                    var filePath2 = Path.Combine(Directory.GetCurrentDirectory(), "UploadedFiles", fileName2);

                    using (var stream = new FileStream(filePath1, FileMode.Create))
                    {
                        await file1.CopyToAsync(stream);
                    }

                    using (var stream = new FileStream(filePath2, FileMode.Create))
                    {
                        await file2.CopyToAsync(stream);
                    }

                   
                    var existingBook = await _context.Book.FindAsync(id);

                    if (existingBook != null)
                    {
                      
                        existingBook.Title = book.Title;
                        existingBook.YearPublished = book.YearPublished;
                        existingBook.NumPages = book.NumPages;
                        existingBook.Description = book.Description;
                        existingBook.Publisher = book.Publisher;
                        existingBook.FrontPage = "../UploadedFiles/" + fileName1;
                        existingBook.DownloadURL = "../UploadedFiles/" + fileName2;
                        existingBook.AuthorId = book.AuthorId;

                        
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }

            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FirstName", book.AuthorId);
            return View(book);
        }


        // GET: Books/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Book == null)
            {
                return Problem("Entity set 'BookstoreContext.Book'  is null.");
            }
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bookstore/Controllers/UserBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace Bookstore.Controllers
{
    public class UserBooksController : Controller
    {
        private readonly BookstoreContext _context;

        public UserBooksController(BookstoreContext context)
        {
            _context = context;
        }

        // GET: UserBooks
        public async Task<IActionResult> Index()
        {
            string userEmail = User.FindFirstValue(ClaimTypes.Email);
            bool isAdmin = User.IsInRole("Admin");

            if (!isAdmin) {
                var userBooks = await _context.UserBooks
                    .Include(u => u.Book)
                    .Where(u => u.AppUser == userEmail)
                    .ToListAsync();
                    return View(userBooks);
            }
            else {
                var userBooks = await _context.UserBooks
                    .Include(u => u.Book)
                    .ToListAsync();
                    return View(userBooks);
            }
            
        }

        // GET: UserBooks/BuyBook
        public async Task<IActionResult> BuyBook(int? bookId)
        {
            if (bookId == null &_context.UserBooks == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(bookId);
            if (book == null)
            {
                return NotFound();
            }

            var signedUser = User.FindFirstValue(ClaimTypes.Email);
            var userBooks = new UserBooks
            {
                AppUser = signedUser,
                BookId = book.Id
            };

            _context.UserBooks.Add(userBooks);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        //WriteReview
        public async Task<IActionResult> WriteReview(int? bookId) {
            
            return RedirectToAction("Create", "Reviews");
        }
        // GET: UserBooks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserBooks == null)
            {
                return NotFound();
            }

            var userBooks = await _context.UserBooks
                .Include(u => u.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userBooks == null)
            {
                return NotFound();
            }

            return View(userBooks);
        }

        // GET: UserBooks/Create
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title");
            return View();
        }

        // POST: UserBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AppUser,BookId")] UserBooks userBooks)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userBooks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Publisher", userBooks.BookId);
            return View(userBooks);
        }

        // GET: UserBooks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserBooks == null)
            {
                return NotFound();
            }

            var userBooks = await _context.UserBooks.FindAsync(id);
            if (userBooks == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Publisher", userBooks.BookId);
            return View(userBooks);
        }

        // POST: UserBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppUser,BookId")] UserBooks userBooks)
        {
            if (id != userBooks.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userBooks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserBooksExists(userBooks.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Publisher", userBooks.BookId);
            return View(userBooks);
        }

        // GET: UserBooks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserBooks == null)
            {
                return NotFound();
            }

            var userBooks = await _context.UserBooks
                .Include(u => u.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userBooks == null)
            {
                return NotFound();
            }

            return View(userBooks);
        }

        // POST: UserBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserBooks == null)
            {
                return Problem("Entity set 'BookstoreContext.UserBooks'  is null.");
            }
            var userBooks = await _context.UserBooks.FindAsync(id);
            if (userBooks != null)
            {
                _context.UserBooks.Remove(userBooks);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserBooksExists(int id)
        {
          return (_context.UserBooks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Bookstore/Views/Books/Create.cshtml
@model Bookstore.Models.Book


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearPublished" class="control-label"></label>
                <input asp-for="YearPublished" class="form-control" />
                <span asp-validation-for="YearPublished" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumPages" class="control-label"></label>
                <input asp-for="NumPages" class="form-control" />
                <span asp-validation-for="NumPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrontPage" class="control-label"></label>
                <input type="file" name="file1" class="form-control" />
                <span asp-validation-for="FrontPage" class="text-danger"></span>
            </div>

            @if (ViewBag.Message != null)
            {
                <div class="alert" style="margin-top:20px">
                    @ViewBag.Message
                </div>
            }

            <div class="form-group">
                <label asp-for="DownloadURL" class="control-label"></label>
                <input type="file" name="file2" class="form-control" />
                <span asp-validation-for="DownloadURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label">Author</label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            
            <div class="form-group">
                <label asp-for="Genres" class="control-label">Genres</label>
                <br />
                @foreach (var genre in ViewBag.Genres)
                {
                    <label>
                        <input type="checkbox" name="selectedGenres" value="@genre.Value" />
                        @genre.Text
                    </label>

                    <br />
                }
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bookstore/Views/Books/Delete.cshtml
@model Bookstore.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FrontPage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownloadURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DownloadURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Bookstore/Views/Books/Details.cshtml
@model Bookstore.Models.Book

@{
    ViewData["Title"] = "Details";
   
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            
            @Html.DisplayNameFor(model => model.FrontPage)
        </dt>
        <dd class="col-sm-10">

            @{
                var fileName1 = Model.FrontPage.Substring(Model.FrontPage.LastIndexOf('/') + 1);
            }
            @if (Model.FrontPage.Contains("http"))
            {
                <img src="@(Model.FrontPage)" alt="front_page" width="200px">
            }
            else
            {
                <img src="/UploadedFiles/@fileName1" alt="front_page" width="200px">
            }

         
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author.FullName)
        </dd>
        <dt class = "col-sm-2">
            Year Published
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            Num Pages
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class="col-sm-2">
            Reviews
        </dt>
        <dd class="col-sm-10">
            @{
                var reviews = ViewBag.Reviews as List<string>;
            }

            @foreach (var comment in reviews)
            {
                <p>Reader's comment: @comment</p>
            }
        </dd>
        @if (User.Identity.IsAuthenticated)
        {

            
            var fileName2 = Model.DownloadURL.Substring(Model.DownloadURL.LastIndexOf('/') + 1);

            <dt class="col-sm-2">
                Download
            </dt>
            <dd class="col-sm-10">
                <a href="/UploadedFiles/@fileName2" download>Download</a>
            </dd>
            
        }

        
        
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
                    }
    <a asp-action="Index">Back to List</a>
</div>

Bookstore/Views/Books/Index.cshtml
@model Bookstore.ViewModels.BookGenreViewModel

<h1>Index</h1>


@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Books" asp-action="Index" method="get">
    <p>
        <select asp-for="BookGenre" asp-items="Model.Genres">
            <option value="">All</option>
        </select>
        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Front Page
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].YearPublished)
            </th>
            <th>
                Rating
            </th>
            @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
            {
                <th>
                    Buy
                </th>
            }
            <!--<th>
            @Html.DisplayNameFor(model => model.Books[0].NumPages)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Books[0].Description)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Books[0].Publisher)
            </th>
            
            <th>
            @Html.DisplayNameFor(model => model.Books[0].DownloadURL)
            </th>
            <th></th>
            -->
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Books) {
        <tr>
            <td>
                 <img src="@item.FrontPage" alt="front_page" width="200px">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearPublished)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.CalculateRating)
            </td>
           <!-- <td>
                @Html.DisplayFor(modelItem => item.NumPages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
            
            <td>
                <a href=@*item.DownloadURL*@>Download</a>
                 </td> -->
                @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
                {

                 <td>
                    <a href="@Url.Action("BuyBook", "UserBooks", new { bookId = item.Id })">Buy</a>
                </td>
                }
            <td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }
                    |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
            </td>
            
        </tr>
}
    </tbody>
</table>

Bookstore/Views/Books/Rating.cshtml
@page
@model List<Book>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Rating</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author</td>
                <td>@book.AverageRating</td>
            </tr>
        }
    </tbody>
</table>